### ISSUE TITLE
tar file error

### ISSUE THREAD

**Issue by my462** [ZhangYuanhan-AI/OmniBenchmark#5]
unexpected end of file for multiple tar files... Can you check it? I download the tar 00 twice and got the same hash5 value.

**Comment by ZhangYuanhan-AI** [comment]
Here:
251426c56f08dc3b8cb18b4de1489fb9  omnibenchmark_v2_onedrive.tar.00
18e7b463ce11572fab820c8775f6f41f  omnibenchmark_v2_onedrive.tar.01
89ea8d280cc0b6884deaa1d7e45aa88a  omnibenchmark_v2_onedrive.tar.02
46e673a9aef7510e93af64e0279d640e  omnibenchmark_v2_onedrive.tar.03
aca566a69626a47e28f4dcfd1fc17320  omnibenchmark_v2_onedrive.tar.04
1faa33017ef351779af9294547cdb0e4  omnibenchmark_v2_onedrive.tar.05
aca9a3374f02d00e85a1cab9b5f79f2a  omnibenchmark_v2_onedrive.tar.06
1eef89cc1c9b5cad7647d6e199612c68  omnibenchmark_v2_onedrive.tar.07
72bbedc5fddad68b703949294f99cf24  omnibenchmark_v2_onedrive.tar.08

**Comment by my462** [comment]
thanks for the md5 value. Now redownloading with IDM again... Much appreicated your help!

**Comment by ZhangYuanhan-AI** [comment]
> thanks for the md5 value. Now redownloading with IDM again... Much appreicated your help!

Feel free to ask about any problems!
